name: CI

on: [push, pull_request]

jobs:
  release:
    name: CI Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '17', '18', '20']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 18.x
        uses: actions/setup-node@master

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
